version: "3.9"
services:
  db:
    image: postgres
    ports: 
      - "5432:5432"
    environment: 
      - POSTGRES_PASSWORD=vFo5Ogz3ugffQoWCgmGD
      - POSTGRES_USER=web3
      - POSTGRES_DB=web3
    volumes:
      - dbdata:/var/lib/postgresql/data
volumes: 
  dbdata: {}  

